#!/usr/bin/env sh
set -eu

root="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$root"

fail() {
  printf 'check-reliability: %s\n' "$1" >&2
  exit 1
}

for file in \
  docs/observability.md \
  docs/evals.md \
  docs/approval-gates.md \
  docs/artifact-contracts.md \
  docs/security-guardrails.md \
  docs/prompt-injection.md \
  docs/ci-quality.md \
  docs/run-memory.md \
  docs/spec-driven-workflow.md \
  docs/benchmark-pack.md \
  docs/workflow-accounting.md \
  docs/qa-to-regression.md \
  docs/shared-state.md \
  docs/human-checkpoints.md \
  docs/inspector.md \
  docs/tool-trust.md \
  docs/mcp-governance.md \
  docs/tool-registry.md \
  docs/tool-safety-rules.md \
  docs/mcp-review-workflow.md \
  docs/external-tool-setup.md \
  docs/integrations-overview.md \
  docs/setup-validation.md \
  docs/degraded-mode.md \
  docs/setup-ux.md \
  docs/integrations/github.md \
  docs/integrations/linear.md \
  docs/legacy-modernization.md \
  docs/repo-archaeology.md \
  docs/onboarding.md \
  docs/next-step-guidance.md \
  docs/guidance-tone.md \
  docs/experience-adaptation.md \
  docs/phase-exit-rules.md \
  docs/next-step-decision-rules.md \
  docs/goal-mode.md \
  docs/goal-safety.md \
  docs/goal-recommendation-rules.md \
  docs/milestone-planning.md \
  docs/compatibility-matrix.md \
  docs/command-mapping.md \
  docs/ecosystem-watch.md \
  docs/ecosystem-opportunities.md \
  docs/hosts/codex-cli.md \
  docs/hosts/claude-code.md \
  docs/hosts/hermes-agent.md \
  docs/hosts/vscode.md \
  docs/hosts/generic.md \
  templates/run-trace.md \
  templates/shared-state.md \
  templates/checkpoint-request.md \
  templates/checkpoint-decision.md \
  templates/run-inspection.md \
  templates/eval-case.md \
  templates/eval-report.md \
  templates/approval-request.md \
  templates/workflow-metrics.md \
  templates/regression-candidate.md \
  templates/regression-task.md \
  templates/benchmark-case.md \
  templates/benchmark-report.md \
  templates/tool-registry-entry.md \
  templates/mcp-server-entry.md \
  templates/mcp-review.md \
  templates/tool-requirements.md \
  templates/integration-status.md \
  templates/integration-health-report.md \
  templates/github-setup-checklist.md \
  templates/linear-setup-checklist.md \
  templates/setup-guidance-quick.md \
  templates/setup-guidance-guided.md \
  templates/legacy-audit.md \
  templates/legacy-risk-report.md \
  templates/modernization-spec.md \
  templates/user-guidance-profile.md \
  templates/next-step-onboarding.md \
  templates/next-step-spec.md \
  templates/next-step-milestone.md \
  templates/next-step-implementation.md \
  templates/next-step-qa.md \
  templates/next-step-regression.md \
  templates/next-step-review.md \
  templates/next-step-ship.md \
  templates/goal-contract.md \
  templates/goal-status.md \
  templates/ecosystem-adopt-issue.md \
  templates/run-memory.md \
  templates/contracts/spec-contract.md \
  templates/contracts/run-memory-contract.md \
  templates/contracts/qa-brief-contract.md \
  templates/contracts/regression-pack-contract.md \
  templates/contracts/trace-contract.md \
  templates/contracts/eval-contract.md \
  commands/hvn-trace.md \
  commands/hvn-eval.md \
  commands/hvn-approve.md \
  commands/hvn-security-check.md \
  commands/hvn-benchmark.md \
  commands/hvn-metrics.md \
  commands/hvn-regression-task.md \
  commands/hvn-state.md \
  commands/hvn-checkpoint.md \
  commands/hvn-inspect.md \
  commands/hvn-tool-review.md \
  commands/hvn-mcp-review.md \
  commands/hvn-setup.md \
  commands/hvn-check-setup.md \
  commands/hvn-validate-integration.md \
  commands/hvn-legacy.md \
  commands/hvn-next.md \
  commands/hvn-goal.md \
  commands/hvn-goal-create.md \
  commands/hvn-goal-status.md \
  commands/hvn-goal-review.md \
  skills/hvn-observability/SKILL.md \
  skills/hvn-eval/SKILL.md \
  skills/hvn-approval-gate/SKILL.md \
  skills/hvn-benchmark/SKILL.md \
  skills/hvn-accounting/SKILL.md \
  skills/hvn-regression-task/SKILL.md \
  skills/hvn-shared-state/SKILL.md \
  skills/hvn-checkpoint/SKILL.md \
  skills/hvn-tool-governance/SKILL.md \
  skills/hvn-tool-setup/SKILL.md \
  skills/hvn-legacy/SKILL.md \
  skills/hvn-next-step/SKILL.md \
  skills/hvn-goal-mode/SKILL.md \
  docs/examples/trace-for-feature-run.md \
  docs/examples/eval-report.md \
  docs/examples/approval-request.md \
  docs/examples/prompt-injection-handling.md \
  docs/examples/artifact-contract-usage.md \
  docs/examples/benchmark-run.md \
  docs/examples/workflow-metrics-report.md \
  docs/examples/qa-to-regression.md \
  docs/examples/shared-state-handoff.md \
  docs/examples/checkpoint-before-risky-change.md \
  docs/examples/run-inspection.md \
  docs/examples/pause-and-resume.md \
  docs/examples/tool-review.md \
  docs/examples/mcp-server-review.md \
  docs/examples/high-risk-tool-approval.md \
  docs/examples/github-setup.md \
  docs/examples/linear-setup.md \
  docs/examples/setup-github-codex.md \
  docs/examples/setup-linear-claude-code.md \
  docs/examples/setup-fallback-manual.md \
  docs/examples/integration-health-check.md \
  docs/examples/optional-tool-not-required.md \
  docs/examples/legacy-repo-audit.md \
  docs/examples/legacy-modernization-plan.md \
  docs/examples/business-logic-extraction.md \
  docs/examples/legacy-to-spec.md \
  docs/examples/legacy-risk-assessment.md \
  docs/examples/next-step-beginner.md \
  docs/examples/next-step-advanced.md \
  docs/examples/post-spec-guidance.md \
  docs/examples/post-qa-guidance.md \
  docs/examples/post-implementation-guidance.md \
  docs/examples/when-guidance-stays-quiet.md \
  docs/examples/goal-from-spec.md \
  docs/examples/goal-for-milestone.md \
  docs/examples/goal-review.md \
  docs/examples/goal-status-handoff.md \
  docs/examples/bad-goal-vs-good-goal.md \
  registry/tools/README.md \
  registry/mcp-servers/README.md \
  reports/ecosystem-sweep/automation.md \
  reports/ecosystem-sweep/tracked-sources.md \
  reports/ecosystem-sweep/latest.md \
  reports/ecosystem-sweep/state.json \
  reports/ecosystem-sweep/draft-issues/README.md \
  examples/evals/starter-set.md
do
  [ -f "$file" ] || fail "missing reliability file: $file"
done

case_count="$(grep -Ec '^[0-9]+\.' examples/evals/starter-set.md | tr -d ' ')"
[ "$case_count" -ge 10 ] || fail "starter eval set must contain at least 10 cases"

printf 'check-reliability: ok\n'
