#!/usr/bin/env sh
set -eu

root="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
cd "$root"

fail() {
  printf 'check-reliability: %s\n' "$1" >&2
  exit 1
}

for file in \
  docs/attribution.md \
  docs/provenance.md \
  docs/wraps-vs-borrows.md \
  docs/attribution-maintenance.md \
  docs/attribution-audit.md \
  docs/licenses.md \
  docs/observability.md \
  docs/evals.md \
  docs/approval-gates.md \
  docs/artifact-contracts.md \
  docs/security-guardrails.md \
  docs/prompt-injection.md \
  docs/ci-quality.md \
  docs/run-memory.md \
  docs/spec-driven-workflow.md \
  docs/README.md \
  docs/information-architecture.md \
  docs/start-here.md \
  docs/quickstart.md \
  docs/intro.md \
  docs/feature-index.md \
  docs/command-index.md \
  docs/use-case-map.md \
  docs/choose-your-path.md \
  docs/glossary.md \
  docs/concept-map.md \
  docs/docs-automation.md \
  docs/wiki-maintenance.md \
  docs/staleness-detection.md \
  docs/doc-owners.md \
  docs/contributing-docs.md \
  docs/whats-new.md \
  docs/recent-doc-updates.md \
  docs/benchmark-pack.md \
  docs/workflow-accounting.md \
  docs/qa-to-regression.md \
  docs/shared-state.md \
  docs/human-checkpoints.md \
  docs/inspector.md \
  docs/tool-trust.md \
  docs/mcp-governance.md \
  docs/tool-registry.md \
  docs/tool-safety-rules.md \
  docs/mcp-review-workflow.md \
  docs/external-tool-setup.md \
  docs/integrations-overview.md \
  docs/setup-validation.md \
  docs/degraded-mode.md \
  docs/setup-ux.md \
  docs/runtime-adaptation.md \
  docs/harness-capability-profiles.md \
  docs/harness-detection.md \
  docs/feature-routing.md \
  docs/runtime-flags.md \
  docs/runtime-fallbacks.md \
  docs/runtime-degraded-mode.md \
  docs/runtime-status.md \
  docs/execution-receipts.md \
  docs/artifact-lineage.md \
  docs/replay-restore.md \
  docs/background-mode.md \
  docs/background-permissions.md \
  docs/background-risk-tiers.md \
  docs/background-task-types.md \
  docs/background-ux.md \
  docs/loop-guards.md \
  docs/echo-chamber-avoidance.md \
  docs/stage-budgets.md \
  docs/integrations/github.md \
  docs/integrations/linear.md \
  docs/legacy-modernization.md \
  docs/repo-archaeology.md \
  docs/onboarding.md \
  docs/business-ideation.md \
  docs/idea-one-pagers.md \
  docs/idea-evaluation-lenses.md \
  docs/idea-research.md \
  docs/idea-validation.md \
  docs/opportunity-memos.md \
  docs/idea-feedback-style.md \
  docs/business-ideation-ux.md \
  docs/idea-research-pipeline.md \
  docs/paved-roads.md \
  docs/next-step-guidance.md \
  docs/guidance-tone.md \
  docs/experience-adaptation.md \
  docs/phase-exit-rules.md \
  docs/next-step-decision-rules.md \
  docs/goal-mode.md \
  docs/goal-safety.md \
  docs/goal-recommendation-rules.md \
  docs/milestone-planning.md \
  docs/controller-agent-integration.md \
  docs/project-orientation.md \
  docs/delegation.md \
  docs/result-ingestion.md \
  docs/controller-executor-compatibility.md \
  docs/harness-compatibility.md \
  docs/harness-watch.md \
  docs/compatibility-matrix.md \
  docs/command-mapping.md \
  docs/portable-artifacts.md \
  docs/open-agent-spec-direction.md \
  docs/schema-versioning.md \
  docs/artifact-mapping.md \
  docs/schema-validation.md \
  docs/ecosystem-watch.md \
  docs/ecosystem-opportunities.md \
  docs/hosts/codex-cli.md \
  docs/hosts/claude-code.md \
  docs/hosts/hermes-agent.md \
  docs/hosts/vscode.md \
  docs/hosts/generic.md \
  docs/guides/using-hvn-with-codex.md \
  docs/guides/using-hvn-with-hermes.md \
  docs/guides/goal-mode-guide.md \
  docs/guides/background-mode-guide.md \
  docs/guides/business-ideation-guide.md \
  docs/guides/paved-roads-guide.md \
  docs/guides/runtime-adaptation-guide.md \
  templates/run-trace.md \
  templates/shared-state.md \
  templates/checkpoint-request.md \
  templates/checkpoint-decision.md \
  templates/run-inspection.md \
  templates/eval-case.md \
  templates/eval-report.md \
  templates/approval-request.md \
  templates/workflow-metrics.md \
  templates/regression-candidate.md \
  templates/regression-task.md \
  templates/benchmark-case.md \
  templates/benchmark-report.md \
  templates/tool-registry-entry.md \
  templates/mcp-server-entry.md \
  templates/mcp-review.md \
  templates/tool-requirements.md \
  templates/integration-status.md \
  templates/integration-health-report.md \
  templates/github-setup-checklist.md \
  templates/linear-setup-checklist.md \
  templates/setup-guidance-quick.md \
  templates/setup-guidance-guided.md \
  templates/harness-capability-profile.md \
  templates/runtime-detection-report.md \
  templates/runtime-route.md \
  templates/runtime-policy.md \
  templates/runtime-status.md \
  templates/execution-receipt.md \
  templates/artifact-lineage.md \
  templates/replay-case.md \
  templates/background-run-contract.md \
  templates/background-run-plan.md \
  templates/background-run-receipt.md \
  templates/permission-request-note.md \
  templates/legacy-audit.md \
  templates/legacy-risk-report.md \
  templates/modernization-spec.md \
  templates/upstream-entry.md \
  templates/attribution-check.md \
  templates/idea-one-pager.md \
  templates/idea-intake.md \
  templates/idea-scorecard.md \
  templates/evidence-vs-assumption.md \
  templates/market-research-brief.md \
  templates/competitor-scan.md \
  templates/customer-problem-research.md \
  templates/validation-plan.md \
  templates/assumption-test.md \
  templates/customer-interview-plan.md \
  templates/smoke-test-plan.md \
  templates/opportunity-memo.md \
  templates/idea-decision.md \
  templates/idea-guided-mode.md \
  templates/idea-fast-mode.md \
  templates/user-guidance-profile.md \
  templates/next-step-onboarding.md \
  templates/next-step-spec.md \
  templates/next-step-milestone.md \
  templates/next-step-implementation.md \
  templates/next-step-qa.md \
  templates/next-step-regression.md \
  templates/next-step-review.md \
  templates/next-step-ship.md \
  templates/goal-contract.md \
  templates/goal-status.md \
  templates/project-orientation.md \
  templates/delegation-brief.md \
  templates/delegation-result.md \
  templates/result-ingestion.md \
  templates/controller-executor-profile.md \
  templates/schema-migration-note.md \
  templates/artifact-mapping.md \
  templates/ecosystem-adopt-issue.md \
  templates/doc-refresh-note.md \
  templates/wiki-update-note.md \
  templates/doc-metadata.md \
  templates/doc-change-checklist.md \
  templates/run-memory.md \
  templates/contracts/spec-contract.md \
  templates/contracts/run-memory-contract.md \
  templates/contracts/qa-brief-contract.md \
  templates/contracts/regression-pack-contract.md \
  templates/contracts/trace-contract.md \
  templates/contracts/eval-contract.md \
  commands/orca-trace.md \
  commands/orca-eval.md \
  commands/orca-approve.md \
  commands/orca-security-check.md \
  commands/orca-benchmark.md \
  commands/orca-metrics.md \
  commands/orca-regression-task.md \
  commands/orca-state.md \
  commands/orca-checkpoint.md \
  commands/orca-inspect.md \
  commands/orca-tool-review.md \
  commands/orca-mcp-review.md \
  commands/orca-setup.md \
  commands/orca-check-setup.md \
  commands/orca-validate-integration.md \
  commands/orca-runtime.md \
  commands/orca-status.md \
  commands/orca-attribution.md \
  commands/orca-idea.md \
  commands/orca-evaluate-idea.md \
  commands/orca-plan-idea.md \
  commands/orca-validate-idea.md \
  commands/orca-controller.md \
  commands/orca-docs.md \
  commands/orca-orient.md \
  commands/orca-schema.md \
  commands/orca-receipt.md \
  commands/orca-lineage.md \
  commands/orca-replay.md \
  commands/orca-restore.md \
  commands/orca-background.md \
  commands/orca-keep-going.md \
  commands/orca-background-status.md \
  commands/orca-legacy.md \
  commands/orca-next.md \
  commands/orca-goal.md \
  commands/orca-goal-create.md \
  commands/orca-goal-status.md \
  commands/orca-goal-review.md \
  commands/orca-delegate.md \
  commands/orca-ingest.md \
  commands/orca-validate-schema.md \
  skills/orca-observability/SKILL.md \
  skills/orca-eval/SKILL.md \
  skills/orca-approval-gate/SKILL.md \
  skills/orca-benchmark/SKILL.md \
  skills/orca-accounting/SKILL.md \
  skills/orca-regression-task/SKILL.md \
  skills/orca-shared-state/SKILL.md \
  skills/orca-checkpoint/SKILL.md \
  skills/orca-tool-governance/SKILL.md \
  skills/orca-tool-setup/SKILL.md \
  skills/orca-runtime-adaptation/SKILL.md \
  skills/orca-receipts/SKILL.md \
  skills/orca-background-mode/SKILL.md \
  skills/orca-legacy/SKILL.md \
  skills/orca-business-ideation/SKILL.md \
  skills/orca-attribution/SKILL.md \
  skills/orca-next-step/SKILL.md \
  skills/orca-goal-mode/SKILL.md \
  skills/orca-controller-mode/SKILL.md \
  skills/orca-delegation/SKILL.md \
  skills/orca-portability/SKILL.md \
  skills/orca-docs-system/SKILL.md \
  docs/examples/trace-for-feature-run.md \
  docs/examples/eval-report.md \
  docs/examples/approval-request.md \
  docs/examples/prompt-injection-handling.md \
  docs/examples/artifact-contract-usage.md \
  docs/examples/benchmark-run.md \
  docs/examples/workflow-metrics-report.md \
  docs/examples/qa-to-regression.md \
  docs/examples/shared-state-handoff.md \
  docs/examples/checkpoint-before-risky-change.md \
  docs/examples/run-inspection.md \
  docs/examples/pause-and-resume.md \
  docs/examples/tool-review.md \
  docs/examples/mcp-server-review.md \
  docs/examples/high-risk-tool-approval.md \
  docs/examples/github-setup.md \
  docs/examples/linear-setup.md \
  docs/examples/setup-github-codex.md \
  docs/examples/setup-linear-claude-code.md \
  docs/examples/setup-fallback-manual.md \
  docs/examples/integration-health-check.md \
  docs/examples/optional-tool-not-required.md \
  docs/examples/runtime-codex-goal.md \
  docs/examples/runtime-claude-manual-fallback.md \
  docs/examples/runtime-no-linear.md \
  docs/examples/runtime-unknown-harness.md \
  docs/examples/runtime-strict-compatibility.md \
  docs/examples/execution-receipt.md \
  docs/examples/artifact-lineage.md \
  docs/examples/replay-after-harness-update.md \
  docs/examples/restore-after-failed-goal.md \
  docs/examples/background-research.md \
  docs/examples/background-refactor-plan.md \
  docs/examples/background-qa-prep.md \
  docs/examples/background-blocked-permission.md \
  docs/examples/background-loop-guard-triggered.md \
  docs/examples/legacy-repo-audit.md \
  docs/examples/legacy-modernization-plan.md \
  docs/examples/business-logic-extraction.md \
  docs/examples/legacy-to-spec.md \
  docs/examples/legacy-risk-assessment.md \
  docs/examples/upstream-entry.md \
  docs/examples/inspiration-vs-wrapper.md \
  docs/examples/third-party-notice.md \
  docs/examples/feature-provenance.md \
  docs/examples/idea-one-pager.md \
  docs/examples/idea-scorecard.md \
  docs/examples/opportunity-memo.md \
  docs/examples/validation-plan.md \
  docs/examples/idea-kill-decision.md \
  docs/examples/idea-pursue-decision.md \
  docs/examples/new-user-path.md \
  docs/examples/hermes-user-path.md \
  docs/examples/codex-user-path.md \
  docs/examples/business-ideation-user-path.md \
  docs/examples/background-mode-user-path.md \
  docs/examples/next-step-beginner.md \
  docs/examples/next-step-advanced.md \
  docs/examples/post-spec-guidance.md \
  docs/examples/post-qa-guidance.md \
  docs/examples/post-implementation-guidance.md \
  docs/examples/when-guidance-stays-quiet.md \
  docs/examples/goal-from-spec.md \
  docs/examples/goal-for-milestone.md \
  docs/examples/goal-review.md \
  docs/examples/goal-status-handoff.md \
  docs/examples/bad-goal-vs-good-goal.md \
  docs/examples/hermes-zip-project-entry.md \
  docs/examples/hermes-to-codex-delegation.md \
  docs/examples/portable-spec-schema.md \
  docs/examples/portable-goal-contract.md \
  docs/examples/schema-migration.md \
  docs/examples/artifact-mapping.md \
  ACKNOWLEDGEMENTS.md \
  NOTICE \
  THIRD_PARTY_NOTICES.md \
  UPSTREAM.md \
  HVN-STATUS.md \
  wiki/Home.md \
  wiki/Getting-Started.md \
  wiki/Core-Concepts.md \
  wiki/Feature-Index.md \
  wiki/Workflow-Index.md \
  wiki/Commands.md \
  wiki/Hosts-and-Harnesses.md \
  wiki/Automation.md \
  wiki/Examples.md \
  wiki/FAQ.md \
  wiki/_Sidebar.md \
  wiki/_Footer.md \
  wiki/Whats-New.md \
  schema/README.md \
  schema/versions/v1/onboarding-summary.schema.json \
  schema/versions/v1/spec.schema.json \
  schema/versions/v1/milestone-plan.schema.json \
  schema/versions/v1/goal-contract.schema.json \
  schema/versions/v1/run-memory.schema.json \
  schema/versions/v1/run-trace.schema.json \
  schema/versions/v1/execution-receipt.schema.json \
  schema/versions/v1/qa-finding.schema.json \
  schema/versions/v1/regression-task.schema.json \
  schema/versions/v1/approval-request.schema.json \
  schema/versions/v1/runtime-status.schema.json \
  schema/examples/spec-v1.json \
  schema/examples/goal-contract-v1.json \
  schema/examples/runtime-status-v1.json \
  registry/tools/README.md \
  registry/mcp-servers/README.md \
  registry/harnesses/README.md \
  registry/harnesses/codex.md \
  registry/harnesses/claude-code.md \
  registry/harnesses/hermes-agent.md \
  registry/harnesses/opencode.md \
  registry/harnesses/cursor.md \
  registry/harnesses/github-copilot.md \
  registry/harnesses/generic.md \
  reports/ecosystem-sweep/automation.md \
  reports/ecosystem-sweep/tracked-sources.md \
  reports/ecosystem-sweep/latest.md \
  reports/ecosystem-sweep/state.json \
  reports/ecosystem-sweep/draft-issues/README.md \
  reports/compatibility/latest.md \
  reports/compatibility/2026-05-30.md \
  examples/evals/starter-set.md
do
  [ -f "$file" ] || fail "missing reliability file: $file"
done

case_count="$(grep -Ec '^[0-9]+\.' examples/evals/starter-set.md | tr -d ' ')"
[ "$case_count" -ge 10 ] || fail "starter eval set must contain at least 10 cases"

printf 'check-reliability: ok\n'
